version: '3.1'

services:
  my-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./my-db-volume:/var/lib/mysql

